// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtXdDcqvkQjyqHFr4Ir4dnZA-iPThOpA',
    appId: '1:286924606564:web:10e02fb1fcacff4fb7e371',
    messagingSenderId: '286924606564',
    projectId: 'iti-final-pro',
    authDomain: 'iti-final-pro.firebaseapp.com',
    storageBucket: 'iti-final-pro.appspot.com',
    measurementId: 'G-85WMDME9EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtyN5Ii6zTCVYkwtKkCE_j2P7sZ7nZaBc',
    appId: '1:286924606564:android:9e0c8252664ccfeab7e371',
    messagingSenderId: '286924606564',
    projectId: 'iti-final-pro',
    storageBucket: 'iti-final-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldIcPU-nlfCKCWC9JBrlr-zlMDldSjFM',
    appId: '1:286924606564:ios:f8680e5d06577f51b7e371',
    messagingSenderId: '286924606564',
    projectId: 'iti-final-pro',
    storageBucket: 'iti-final-pro.appspot.com',
    iosClientId: '286924606564-e2of1gads1vlrues3n6siennatov2iun.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAldIcPU-nlfCKCWC9JBrlr-zlMDldSjFM',
    appId: '1:286924606564:ios:d2788981f27815d5b7e371',
    messagingSenderId: '286924606564',
    projectId: 'iti-final-pro',
    storageBucket: 'iti-final-pro.appspot.com',
    iosClientId: '286924606564-qucp5k28kpe5nr9l4um6iv9jcmku78bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalPro.RunnerTests',
  );
}
